allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(Javadoc) {
        options.addStringOption('encoding', 'UTF-8')
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

ext {
    compileSdkVersion = 36
    minSdkVersion = 21
    targetSdkVersion = 36

    assert minSdkVersion <= targetSdkVersion : "minSdkVersion too big"
    assert targetSdkVersion <= compileSdkVersion : "targetSdkVersion too big"
}